"""Migration

Revision ID: b8e6b7e47cb8
Revises: 4e551a14e78c
Create Date: 2022-05-15 18:02:44.010839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8e6b7e47cb8'
down_revision = '4e551a14e78c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogs', 'date')
    # ### end Alembic commands ###
